name: CD
on:
  release:
    types:
      - published

jobs:
  release:
    name: "Release"
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Gitea
        uses: docker/build-push-action@v2
        with:
          tags: covergates/test-gitea:latest
          context: ./images/gitea
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Build MySQL
        uses: docker/build-push-action@v2
        with:
          tags: covergates/test-mysql:latest
          context: ./images/mariadb
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Build Covergates
        uses: docker/build-push-action@v2
        with:
          tags: covergates/test-covergates:latest
          context: ./images/covergates
          platforms: linux/amd64,linux/arm64,linux/arm/v7
