name: CD
on:
  release:
    types:
      - published

jobs:
  release:
    name: "Release"
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Gitea
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: covergates/gitea-test
          tags: latest
          context: ./images/gitea
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Build MySQL
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: covergates/mysql-test
          tags: latest
          context: ./images/mariadb
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Build Covergates
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: covergates/covergates-test
          tags: latest
          context: ./images/covergates
          platforms: linux/amd64,linux/arm64,linux/arm/v7
